### ISSUE TITLE
Linker error - relocation R_X86_64_32S against `.text' can not be used when making a shared object; recompile with -fPIC

### ISSUE THREAD

**Issue by alex285** [ikeydoherty/budgie-next#1]
/usr/bin/ld: budgie_next_panel-Animation.o: relocation R_X86_64_32S against `.text' can not be used when making a shared object; recompile with -fPIC
budgie_next_panel-Animation.o: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
Makefile:496: recipe for target 'budgie-next-panel' failed
make[3]: *** [budgie-next-panel] Error 1

**Comment by ikeydoherty** [comment]
For now:
`./autogen.sh --prefix=/usr CFLAGS="-O2 -fPIC"`

Shouldn't actually be required at all here, we build a single binary for `budgie-next-pane`l. Distro/toolchain details?

**Comment by alex285** [comment]
CFLAGS="-O2 -fPIC" didnt work.
Distro : Arch
GCC: gcc 4.9.2-4 (64bit)

**Comment by alex285** [comment]
Thanks!

**Comment by ikeydoherty** [comment]
Most welcome :)
